### ISSUE TITLE
Unable to reproduce the result of 3b_vs_1h_1m.

### ISSUE THREAD

**Issue by TianQi-777** [TonghanWang/NDQ#12]
I found that `bane_vs_hM` is indeed the `3b_vs_1h_1m` map in the paper, but the result of performance according to the default config is always 0. Can you provide the training hyperparameters for this map?
In addition, do all StarCraft maps use the same default hyperparameters?

**Comment by TianQi-777** [comment]
I successfully reproduced

**Comment by chenrongmin** [comment]
Hello, I trained 3b-vs_1h-1m on pymarl2 and the result was 0. How did you solve this problem
