### ISSUE TITLE
How to create new envs

### ISSUE THREAD

**Issue by GoingMyWay** [TonghanWang/NDQ#6]
Hi, I found in your paper, you used new envs which seems to be created by you, how can I create such envs? Are there any tutorials?

**Comment by TonghanWang** [comment]
Hi, you can create your own maps by StarCraft II map editor.  Create a RL unit as follows: 

Open editor, data editor, unit tab
Right click and click add new unit
Name the new unit, click suggest right below it
Leave the "parent:" row alone. That determines what we're making. We want to make a unit
Select the unit you want to copy (bottom of the new opened window, "copy from" row) e.g. zealot if you're copying zealot
Set the "Object family:," "Race:," and "Object Type:" as desired. THESE DO NOTHING but make it easier for you to find your new unit once it's made. e.g. you probably want a new zerg unit to be in the zerg section when you go to place it on your map or something.
Press okay, you're almost done
Click the plus sign on the data editor tabs, go to edit actor data, actors
Click the new actors tab
Right click and click add new actor
Name it and click suggest like before
Change the "Actor Type:" row to unit
Select what you want to copy from (bottom of the new opened window again) e.g. zealot if you're coping a zealot
Press okay
Click on your new actor
At the bottom right of the window where it says "Token" and then "Unit Name," change the unit name to the name of your unit e.g. Zealot RL
Go back to the Unit tab, find the new unit and modify the following fields:
(Basic) Stats: Supplies - 0
Combat: Default Acquire Level - Passive
Behaviour: Response - No Response


You can start from an existing SMAC map and add new RL units. After that, click "Tiggers" and edit the function "Spawn" to decide which and how many agents are included in the new map. You can also edit the function "Enemy Attack" there to change the attack mode of the enemies.

**Comment by GoingMyWay** [comment]
> Hi, you can create your own maps by StarCraft II map editor. Create a RL unit as follows:
> 
> Open editor, data editor, unit tab
> Right click and click add new unit
> Name the new unit, click suggest right below it
> Leave the "parent:" row alone. That determines what we're making. We want to make a unit
> Select the unit you want to copy (bottom of the new opened window, "copy from" row) e.g. zealot if you're copying zealot
> Set the "Object family:," "Race:," and "Object Type:" as desired. THESE DO NOTHING but make it easier for you to find your new unit once it's made. e.g. you probably want a new zerg unit to be in the zerg section when you go to place it on your map or something.
> Press okay, you're almost done
> Click the plus sign on the data editor tabs, go to edit actor data, actors
> Click the new actors tab
> Right click and click add new actor
> Name it and click suggest like before
> Change the "Actor Type:" row to unit
> Select what you want to copy from (bottom of the new opened window again) e.g. zealot if you're coping a zealot
> Press okay
> Click on your new actor
> At the bottom right of the window where it says "Token" and then "Unit Name," change the unit name to the name of your unit e.g. Zealot RL
> Go back to the Unit tab, find the new unit and modify the following fields:
> (Basic) Stats: Supplies - 0
> Combat: Default Acquire Level - Passive
> Behaviour: Response - No Response
> 
> You can start from an existing SMAC map and add new RL units. After that, click "Tiggers" and edit the function "Spawn" to decide which and how many agents are included in the new map. You can also edit the function "Enemy Attack" there to change the attack mode of the enemies.

Great, very detailed steps, I will try it, thanks. Sorry for my another question: how do you make the video?  Do you use the save_replay of SMAC?

**Comment by TonghanWang** [comment]
Yes, we use the save_replay of SMAC. 

1. Set save_replay to True
2. Specify _checkpoint_path_
3. Set _runner_ to _episode_
4. Set _batch_size_run_ to 1

**Comment by GoingMyWay** [comment]
> Yes, we use the save_replay of SMAC.
> 
> 1. Set save_replay to True
> 2. Specify _checkpoint_path_
> 3. Set _runner_ to _episode_
> 4. Set _batch_size_run_ to 1

Thanks, I load the model and evaluate and save the replay.

**Comment by TonghanWang** [comment]
Great!

We are willing to help if you encounter other questions when creating new maps.
