### ISSUE TITLE
How to choose GPU #1 if you execute commands in conda env?

### ISSUE THREAD

**Issue by yyf17** [TonghanWang/NDQ#8]
Ask a question:
If you execute the command in docker to select GPU #1:
```
NV_GPU=1 docker run ......
```
How to choose GPU #1 if you execute commands in conda env?
```
python3 src/main.py --config=......
```

**Comment by TonghanWang** [comment]
Hi! Sorry for the late reply!

I think you can try to export the environment variable CUDA_VISIBLE_DEVICES=x if you want to select GPU #x.

**Comment by yyf17** [comment]
@TonghanWang Thank You.
